apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo
  namespace: sre-k8s04u-prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-demo
  template:
    metadata:
      labels:
        app: node-demo
    spec:
      containers:
      - name: node-demo
        image: eyctpeu-sre-docker-dev-eu.jfrog.io/sre-docker/node:469123
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 5m
            memory: 16Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 2000
      imagePullSecrets:
        - name: sreregistry
---
kind: Service
metadata:
  name: node-demo-svc
  namespace: sre-k8s04u-prod
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: node-demo
